---
Organizations:
  - Name: Org1
    MspID: Org1MSP
    Peers:
      - Peer0
Channels:
  - Name: mychannel
    Organizations:
      - Org1
Orderers:
  - Name: orderer.example.com
    URL: orderer.example.com:7050
Peers:
  - Name: peer0.org1.example.com
    URL: peer0.org1.example.com:7051
    Events: peer0.org1.example.com:7053