name: "network-config"
version: "1.0"
client:
  organization: Org1
organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpc://localhost:7051
certificateAuthorities:
  ca.org1.example.com:
    url: http://localhost:7054
    caName: ca-org1